spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://14.103.140.246:3306/kjx?useUnicode=true&characterEncoding=utf8&useSsl=false
    username: root
    password: mysql_YCKaK5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  resources:
    static-locations: classpath:/static/,file:${user.dir}/image_out/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8181
