spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.126.146.178:3306/kjx?useUnicode=true&characterEncoding=utf8&useSsl=false
    username: kjx
    password: MN4M7xmJxD3Cb5iy
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  resources:
    static-locations: classpath:/static/,file:${user.dir}/image_out/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8181
